export const SAVE_SETTINGS = "SAVE_SETTINGS";
export const CHANGE_URL = "CHANGE_URL";

export const CHANGE_METHOD = "CHANGE_METHOD";

export const ADD_PARAMETER = "CHANGE_PARAMETER";
export const REMOVE_PARAMETER = "REMOVE_PARAMETER";
export const CHANGE_PARAMETER_KEY = "CHANGE_PARAMETER_KEY";
export const CHANGE_PARAMETER_VALUE = "CHANGE_PARAMETER_VALUE";
export const CHANGE_PARAMETER_CHECK = "CHANGE_PARAMETER_CHECK";

export const UPDATE_RESPONSE = "UPDATE_RESPONSE";

export const UPDATE_VIEW_RESPONSE_OPTION_TAB = "UPDATE_VIEW_RESPONSE_OPTION_TAB";

export const UPDATE_IS_LOADING = "UPDATE_IS_LOADING";