export const SAVE_SETTINGS = "SAVE_SETTINGS";
export const CHANGE_URL = "CHANGE_URL";

export const CHANGE_METHOD = "CHANGE_METHOD";

export const ADD_PARAMETER = "CHANGE_PARAMETER";
export const RESET_PARAMETERS = "RESET_PARAMETERS";
export const REMOVE_PARAMETER = "REMOVE_PARAMETER";
export const UPDATE_PARAMETERS = "UPDATE_PARAMETERS";

export const UPDATE_RESPONSE = "UPDATE_RESPONSE";
export const UPDATE_RESPONSE_TAB = "UPDATE_RESPONSE_TAB";

export const UPDATE_RESPONSE_IS_LOADING = "UPDATE_RESPONSE_IS_LOADING";

